int32 n  # N-ésimo primo a encontrar
---
int32 result  # Resposta final com o número primo encontrado
---
int32 current_prime  # Feedback do número primo atual encontrado
int32 current_count  # Feedback do contador de primos encontrados